name: kafka-host
networks:
    external_host_network:
        name: external_host_network
        external: true
services:
    zookeeper:
        container_name: zookeeper
        image: debezium/zookeeper
        ports:
            - '2181:2181'
            - '2888:2888'
            - '3888:3888'
        networks:
            - external_host_network
    kafka:
        container_name: kafka
        image: bitnami/kafka
        restart: unless-stopped
        ports:
            - '9094:9094'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        depends_on:
            zookeeper:
                condition: service_started
        networks:
            - external_host_network
    kafka_ui:
        container_name: kafka-ui
        restart: unless-stopped
        image: provectuslabs/kafka-ui:latest
        ports:
            - '9080:8080'
        environment:
            DYNAMIC_CONFIG_ENABLED: true
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        depends_on:
            kafka:
                condition: service_started
        networks:
            - external_host_network
    connect:
        container_name: kafka-connector
        image: debezium/connect
        ports:
            - '8083:8083'
        links:
            - kafka
        environment:
            - BOOTSTRAP_SERVERS=kafka:9092
            - GROUP_ID=1
            - CONFIG_STORAGE_TOPIC=kafka_connect_configs
            - OFFSET_STORAGE_TOPIC=kafka_connect_offsets
            - STATUS_STORAGE_TOPIC=kafka_connect_statuses
        networks:
            - external_host_network