name: kafka-host
networks:
    external_host_network:
        name: external_host_network
        external: true
services:
    kafka:
        container_name: kafka
        image: bitnami/kafka
        restart: unless-stopped
        ports:
            - '9094:9094'
        environment:
            - KAFKA_CFG_NODE_ID=1
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_KRAFT_MODE=true
        networks:
            - external_host_network
    kafka_ui:
        container_name: kafka-ui
        restart: unless-stopped
        image: provectuslabs/kafka-ui:latest
        ports:
            - '9080:8080'
        environment:
            DYNAMIC_CONFIG_ENABLED: true
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        depends_on:
            kafka:
                condition: service_started
        networks:
            - external_host_network